<a href="https://colab.research.google.com/github/thanaprondtn/python_dataviz2024/blob/main/Exam2_653020570_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import os

# Replace with your actual folder path in Google Drive
path = '/content/drive/MyDrive/Data_Viz_2024_Data570-8'

# List of CSV file names
file_names = ['crime_scene_report.csv', 'drivers_license.csv', 'interview.csv', 'income.csv', 'get_fit_now_member.csv', 'get_fit_now_check_in.csv', 'facebook_event_checkin.csv', 'person.csv']

# Create an empty list to store dataframes
dataframes = []

# Loop through each file and read it into a dataframe
for file_name in file_names:
  file_path = os.path.join(path, file_name)
  df = pd.read_csv(file_path)
  dataframes.append(df)

# Now you have a list of dataframes that you can work with
# For example, print the first dataframe
print(dataframes[0])

          date     type                                        description  \
0     20180115  robbery  A Man Dressed as Spider-Man Is on a Robbery Spree
1     20180115   murder                  Life? Dont talk to me about life.
2     20180115   murder  Mama, I killed a man, put a gun against his he...
3     20180215   murder                         REDACTED REDACTED REDACTED
4     20180215   murder  Someone killed the guard! He took an arrow to ...
...        ...      ...                                                ...
1223  20180430  bribery                                                 \n
1224  20180430    fraud                  ‘Why not?’ said the March Hare.\n
1225  20180430  assault                                                 \n
1226  20180501  assault  be NO mistake about it: it was neither more no...
1227  20180115   murder  Security footage shows that there were 2 witne...

              city
0              NYC
1           Albany
2             Reno
3         SQL City
4         SQL City
...            ...
1223  Garden Grove
1224         Houma
1225       Fontana
1226       Trenton
1227      SQL City

[1228 rows x 4 columns]

In [4]:
# prompt: จาก crime_scene_report.csv ให้เลือก type ที่เป็น murder และ date คือ 20180115 และ city คือ SQL City

# Assuming 'crime_scene_report.csv' is the first file in the list
crime_df = dataframes[0]

# Filter the dataframe
filtered_df = crime_df[(crime_df['type'] == 'murder') & (crime_df['date'] == 20180115) & (crime_df['city'] == 'SQL City')]
filtered_df

,date,type,description,city
1227,20180115,murder,Security footage shows that there were 2 witne...,SQL City

In [5]:
# prompt: who lives at the last house on "Northwestern Dr"

# Assuming 'person.csv' is the last file in the list
person_df = dataframes[-1]

# Filter the dataframe for residents on Northwestern Dr, sort by address number, and get the last row
last_resident = person_df[person_df['address_street_name'] == 'Northwestern Dr'].sort_values('address_number', ascending=True).iloc[-1]

last_resident

id                               14887
name                    Morty Schapiro
license_id                      118009
address_number                    4919
address_street_name    Northwestern Dr
ssn                          111564949
Name: 499, dtype: object

In [8]:
# prompt: หา คนที่ชื่อมีคำว่า Annabel และ ที่อยู่มีคำว่า Franklin

# Assuming 'person.csv' is the last file in the list
person_df = dataframes[-1]

# Filter the dataframe for names containing "Annabel" and address containing "Franklin"
filtered_person_df = person_df[(person_df['name'].str.contains("Annabel")) & (person_df['address_street_name'].str.contains("Franklin"))]
filtered_person_df

,id,name,license_id,address_number,address_street_name,ssn
665,16371,Annabel Miller,490173,103,Franklin Ave,318771143

In [9]:
# prompt: หา interview ของ id 14887 และ 16371

# Assuming 'interview.csv' is the third file in the list
interview_df = dataframes[2]

# Filter the dataframe for interview ids 14887 and 16371
interview_filtered = interview_df[interview_df['person_id'].isin([14887, 16371])]
interview_filtered

      person_id                                         transcript
4988      14887  I heard a gunshot and then saw a man run out. ...
4989      16371  I saw the murder happen, and I recognized the ...

In [35]:
# เชื่อมตาราง person กับ  drivers_license
person_df = dataframes[-1]
drivers_license_df = dataframes[1]

# Merge the two dataframes on the 'id' column in person and 'person_id' column in drivers_license
person_data = pd.merge(person_df, drivers_license_df, left_on='license_id', right_on='id', how='inner')

person_data

,id_x,name,license_id,address_number,address_street_name,ssn,id_y,age,height,eye_color,hair_color,gender,plate_number,car_make,car_model
0,10000,Christoper Peteuil,993845,624,Bankhall Ave,747714076,993845,46,59,black,green,male,557472,Chrysler,Town & Country
1,10007,Kourtney Calderwood,861794,2791,Gustavus Blvd,477972044,861794,54,74,black,white,female,3P6DMS,BMW,M Roadster
2,10010,Muoi Cary,385336,741,Northwestern Dr,828638512,385336,24,79,blue,green,female,GM6Y5J,Mercedes-Benz,CLS-Class
3,10016,Era Moselle,431897,1987,Wood Glade St,614621061,431897,22,75,amber,red,female,461S1M,Ford,Ranger
4,10025,Trena Hornby,550890,276,Daws Hill Way,223877684,550890,45,60,blue,black,female,8030O8,Toyota,Tacoma Xtra
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10001,99936,Luba Benser,274427,680,Carnage Blvd,685095054,274427,26,55,green,blonde,female,3O06O3,Ford,Explorer
10002,99941,Roxana Mckimley,975942,1613,Gate St,512136801,975942,87,54,blue,white,female,PYO673,Volvo,XC70
10003,99965,Cherie Zeimantz,287627,3661,The Water Ave,362877324,287627,29,58,black,brown,female,Z784RR,Audi,S5
10004,99982,Allen Cruse,251350,3126,N Jean Dr,348734531,251350,66,61,blue,blonde,male,CJ2QC2,Buick,LaCrosse
10005,99990,Vance Hunten,830407,3056,Lancefield St,896677562,830407,61,76,green,white,male,H55UF5,Chevrolet,Silverado 3500

In [36]:
# เชื่อมตาราง person_data กับ  get_fit_now_member
get_fit_now_member_df = dataframes[4]

test_df = pd.merge(person_data, get_fit_now_member_df, left_on='id_x', right_on='person_id', how='inner')

test_df

,id_x,name_x,license_id,address_number,address_street_name,ssn,id_y,age,height,eye_color,hair_color,gender,plate_number,car_make,car_model,id,person_id,name_y,membership_start_date,membership_status
0,10319,Tama Mazy,706440,834,N Gateway Dr,169669311,706440,51,74,green,blue,female,O34O8E,Acura,RL,3F8N0,10319,Tama Mazy,20171021,gold
1,10325,Bruna Sumlin,340579,3808,N Bartlett Ave,898899969,340579,32,73,green,green,female,GRN3XK,Mitsubishi,Eclipse,77Q7L,10325,Bruna Sumlin,20170604,silver
2,10615,Harold Fullmer,611876,804,Riedell Circle,421328353,611876,72,66,green,grey,male,HLTY17,Ford,Expedition,72244,10615,Harold Fullmer,20170721,gold
3,10815,Adriane Pelligra,952073,948,Emba Ave,243639527,952073,51,59,amber,grey,female,KPF728,Lincoln,Aviator,1AE2H,10815,Adriane Pelligra,20170816,silver
4,10833,Queen Radigan,573165,2910,Claire St,352925729,573165,62,79,blue,grey,female,LR31RK,Chevrolet,S10,3DC24,10833,Queen Radigan,20180320,gold
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178,98782,Sarina Overpeck,755127,3083,Lincoln Mill Way,160772507,755127,23,58,brown,brown,female,775L2V,Pontiac,Sunfire,0T622,98782,Sarina Overpeck,20171109,gold
179,99037,Adrienne Fleishman,926354,1402,Lowood Way,907750296,926354,73,62,amber,brown,female,A07LUD,GMC,Envoy,CGQ1A,99037,Adrienne Fleishman,20170718,regular
180,99277,Pia Ruthenberg,187981,1682,Dunleith St,877723489,187981,28,54,amber,blonde,female,M34K30,GMC,Yukon XL 1500,RMX31,99277,Pia Ruthenberg,20171129,silver
181,99462,Darren Yahraus,684933,1553,E Scranton Way,331245339,684933,33,60,brown,white,male,0D1OTA,Infiniti,I,MYQ6A,99462,Darren Yahraus,20170712,silver
182,99602,Joline Hollering,383435,3021,Celilo St,226217805,383435,29,64,black,blonde,female,U34X7P,Aston Martin,DB9,D2KY6,99602,Joline Hollering,20170220,gold

In [40]:
result_df = test_df[(test_df['id'].str.contains('48Z')) & (test_df['membership_status'] == 'gold') & (test_df['plate_number'].str.contains('H42W'))]

result_df

,id_x,name_x,license_id,address_number,address_street_name,ssn,id_y,age,height,eye_color,hair_color,gender,plate_number,car_make,car_model,id,person_id,name_y,membership_start_date,membership_status
115,67318,Jeremy Bowers,423327,530,"Washington Pl, Apt 3A",871539279,423327,30,70,brown,brown,male,0H42W2,Chevrolet,Spark LS,48Z55,67318,Jeremy Bowers,20160101,gold

In [41]:
# เชื่อมตาราง test_df กับ  get_fit_now_check_in
get_fit_now_check_in_df = dataframes[5]

test2_df = pd.merge(test_df, get_fit_now_check_in_df, left_on='id', right_on='membership_id')

test2_df

,id_x,name_x,license_id,address_number,address_street_name,ssn,id_y,age,height,eye_color,...,car_model,id,person_id,name_y,membership_start_date,membership_status,membership_id,check_in_date,check_in_time,check_out_time
0,10319,Tama Mazy,706440,834,N Gateway Dr,169669311,706440,51,74,green,...,RL,3F8N0,10319,Tama Mazy,20171021,gold,3F8N0,20180426,1183,1187
1,10319,Tama Mazy,706440,834,N Gateway Dr,169669311,706440,51,74,green,...,RL,3F8N0,10319,Tama Mazy,20171021,gold,3F8N0,20170816,193,258
2,10319,Tama Mazy,706440,834,N Gateway Dr,169669311,706440,51,74,green,...,RL,3F8N0,10319,Tama Mazy,20171021,gold,3F8N0,20171208,318,925
3,10319,Tama Mazy,706440,834,N Gateway Dr,169669311,706440,51,74,green,...,RL,3F8N0,10319,Tama Mazy,20171021,gold,3F8N0,20180125,432,902
4,10319,Tama Mazy,706440,834,N Gateway Dr,169669311,706440,51,74,green,...,RL,3F8N0,10319,Tama Mazy,20171021,gold,3F8N0,20170720,298,625
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2697,99602,Joline Hollering,383435,3021,Celilo St,226217805,383435,29,64,black,...,DB9,D2KY6,99602,Joline Hollering,20170220,gold,D2KY6,20170221,78,186
2698,99602,Joline Hollering,383435,3021,Celilo St,226217805,383435,29,64,black,...,DB9,D2KY6,99602,Joline Hollering,20170220,gold,D2KY6,20180421,769,1134
2699,99602,Joline Hollering,383435,3021,Celilo St,226217805,383435,29,64,black,...,DB9,D2KY6,99602,Joline Hollering,20170220,gold,D2KY6,20170629,769,1173
2700,99602,Joline Hollering,383435,3021,Celilo St,226217805,383435,29,64,black,...,DB9,D2KY6,99602,Joline Hollering,20170220,gold,D2KY6,20170604,1153,1190
2701,99602,Joline Hollering,383435,3021,Celilo St,226217805,383435,29,64,black,...,DB9,D2KY6,99602,Joline Hollering,20170220,gold,D2KY6,20171107,623,924

In [45]:
filtered_check_ins = test2_df[(test2_df['check_in_date'] == 20180109)]
filtered_check_ins

,id_x,name_x,license_id,address_number,address_street_name,ssn,id_y,age,height,eye_color,...,car_model,id,person_id,name_y,membership_start_date,membership_status,membership_id,check_in_date,check_in_time,check_out_time
36,10815,Adriane Pelligra,952073,948,Emba Ave,243639527,952073,51,59,amber,...,Aviator,1AE2H,10815,Adriane Pelligra,20170816,silver,1AE2H,20180109,461,944
226,15247,Shondra Ledlow,108978,2906,Chuck Dr,492143109,108978,70,56,brown,...,Rabbit,X0643,15247,Shondra Ledlow,20170521,silver,X0643,20180109,957,1164
288,16371,Annabel Miller,490173,103,Franklin Ave,318771143,490173,35,65,green,...,Yaris,90081,16371,Annabel Miller,20160208,gold,90081,20180109,1600,1700
609,28073,Zackary Cabotage,402017,3823,S Winthrop Ave,367741547,402017,45,81,black,...,M5,UK1F2,28073,Zackary Cabotage,20170818,silver,UK1F2,20180109,344,518
705,31523,Blossom Crescenzo,737886,1245,Ruxshire St,753962462,737886,33,72,brown,...,Navigator L,7MWHJ,31523,Blossom Crescenzo,20180309,regular,7MWHJ,20180109,273,885
1325,55662,Sarita Bartosh,556026,1031,Legacy Pointe Blvd,564780417,556026,44,58,amber,...,Pacifica,XTE42,55662,Sarita Bartosh,20170524,gold,XTE42,20180109,486,1124
1639,67318,Jeremy Bowers,423327,530,"Washington Pl, Apt 3A",871539279,423327,30,70,brown,...,Spark LS,48Z55,67318,Jeremy Bowers,20160101,gold,48Z55,20180109,1530,1700
2138,83186,Burton Grippe,915564,484,Lemcrow Way,426280783,915564,33,62,green,...,Fortwo,6LSTG,83186,Burton Grippe,20170214,gold,6LSTG,20180109,399,515
2386,92736,Carmen Dimick,890722,2965,Kilmaine Circle,622279052,890722,60,61,green,...,TT,GE5Q8,92736,Carmen Dimick,20170618,gold,GE5Q8,20180109,367,959

In [68]:
interview_df = dataframes[2]

interview_67318 = interview_df[interview_df['person_id'] == 67318]

interview_67318

      person_id                                         transcript
4990      67318  I was hired by a woman with a lot of money. I ...

In [66]:
facebook_event_checkin_df = dataframes[6]

test_h_df = pd.merge(person_data, facebook_event_checkin_df, left_on='id_x', right_on='person_id')

test_h_df

,id_x,name,license_id,address_number,address_street_name,ssn,id_y,age,height,eye_color,hair_color,gender,plate_number,car_make,car_model,person_id,event_id,event_name,date
0,10000,Christoper Peteuil,993845,624,Bankhall Ave,747714076,993845,46,59,black,green,male,557472,Chrysler,Town & Country,10000,241,Steinbach's Guideline for Systems Programming\n,20170306
1,10000,Christoper Peteuil,993845,624,Bankhall Ave,747714076,993845,46,59,black,green,male,557472,Chrysler,Town & Country,10000,1137,The Universe is laughing behind your back\n,20171130
2,10007,Kourtney Calderwood,861794,2791,Gustavus Blvd,477972044,861794,54,74,black,white,female,3P6DMS,BMW,M Roadster,10007,6447,Green light in A.M. for new projects. Red lig...,20170925
3,10007,Kourtney Calderwood,861794,2791,Gustavus Blvd,477972044,861794,54,74,black,white,female,3P6DMS,BMW,M Roadster,10007,4273,Modern man is the missing link between apes an...,20171017
4,10010,Muoi Cary,385336,741,Northwestern Dr,828638512,385336,24,79,blue,green,female,GM6Y5J,Mercedes-Benz,CLS-Class,10010,3581,upon to act in accordance with the dictates of...,20180319
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20003,99965,Cherie Zeimantz,287627,3661,The Water Ave,362877324,287627,29,58,black,brown,female,Z784RR,Audi,S5,99965,8433,"""That must be wonderful! I don't understand i...",20171202
20004,99965,Cherie Zeimantz,287627,3661,The Water Ave,362877324,287627,29,58,black,brown,female,Z784RR,Audi,S5,99965,9110,pedestrians.\n,20170705
20005,99982,Allen Cruse,251350,3126,N Jean Dr,348734531,251350,66,61,blue,blonde,male,CJ2QC2,Buick,LaCrosse,99982,4507,Don't cook tonight -- starve a rat today!\n,20170609
20006,99982,Allen Cruse,251350,3126,N Jean Dr,348734531,251350,66,61,blue,blonde,male,CJ2QC2,Buick,LaCrosse,99982,3901,Do not drink coffee in early A.M. It will kee...,20180404
20007,99990,Vance Hunten,830407,3056,Lancefield St,896677562,830407,61,76,green,white,male,H55UF5,Chevrolet,Silverado 3500,99990,2499,taught how _n_o_t to. So it is with the great...,20170506

In [69]:
result_df = test_h_df[(test_h_df['height'].between(65, 67)) &
                      (test_h_df['hair_color'] == 'red') &
                      (test_h_df['car_make'] == 'Tesla') &
                      (test_h_df['car_model'] == 'Model S') &
                      (test_h_df['event_name'] == 'SQL Symphony Concert') &
                      (test_h_df['date'].astype(str).str[:6] == '201712')]
result_df

,id_x,name,license_id,address_number,address_street_name,ssn,id_y,age,height,eye_color,hair_color,gender,plate_number,car_make,car_model,person_id,event_id,event_name,date
19955,99716,Miranda Priestly,202298,1883,Golden Ave,987756388,202298,68,66,green,red,female,500123,Tesla,Model S,99716,1143,SQL Symphony Concert,20171206
19956,99716,Miranda Priestly,202298,1883,Golden Ave,987756388,202298,68,66,green,red,female,500123,Tesla,Model S,99716,1143,SQL Symphony Concert,20171212
19957,99716,Miranda Priestly,202298,1883,Golden Ave,987756388,202298,68,66,green,red,female,500123,Tesla,Model S,99716,1143,SQL Symphony Concert,20171229

In [70]:
income_df = dataframes[3]

result = income_df[income_df['ssn'] == 987756388]

result

            ssn  annual_income
7422  987756388         310000